#!/bin/bash
# 
# THIS TEMPLATE CONTAINS DUMMY VALUES.
# PLEASE ENSURE ALL VARIABLES ARE SET.
# IF NOT USED (e,g, certs in TEST), SET TO EMPTY STRING
# 

# COMMON SETTINGS
export ML_ADMIN=admin
export ML_PASSWORD=admin
export ML_PROTOCOL=http
export ML_DATABASE=Documents

# LOCAL SETTINGS
export ML_LOCAL_ADMIN=admin
export ML_LOCAL_PASSWORD=admin
export ML_LOCAL_PROTOCOL=http
export ML_LOCAL_HOST=docker.cluster1-node1.internal
export ML_LOCAL_CLUSTER_NAME=cluster1
export ML_LOCAL_CERT_PATH=
export ML_LOCAL_CERT_PASSWORD=

# FOREIGN SETTINGS
export ML_FOREIGN_ADMIN=admin
export ML_FOREIGN_PASSWORD=admin
export ML_FOREIGN_PROTOCOL=http
export ML_FOREIGN_HOST=docker.cluster2-node1.internal
export ML_FOREIGN_CLUSTER_NAME=cluster2
export ML_FOREIGN_CERT_PATH=
export ML_FOREIGN_CERT_PASSWORD=

