version: '3.8'

services:
  marklogic:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/app
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8041:8041"
      - "8042:8041"
      - "7997:7997"
      - "7998:7998"
    hostname: simple-ml-host
    container_name: simple-ml 
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=false
      - TZ=Europe/Amsterdam
